### ISSUE TITLE
Could not find tools.jar

### ISSUE THREAD

**Issue by Adri22** [spring-projects/eclipse-integration-gradle#100]
Regardless of whether JAVA_HOME in System-Variables is set or not, tools.jar from the existing jdk in Program Files/Java can not be found while running "refresh all" on an gradle-based project.

**Comment by kdvolder** [comment]
Make sure that your workspace default JRE points to a JDK and not a JRE. THe JVM used by gradle inside STS is determined from workspace default, not from some external environment variable.
