### ISSUE TITLE
Gradle-STS-to-Buildship message

### ISSUE THREAD

**Issue by paulvi** [spring-projects/eclipse-integration-gradle#104]
![gradle-sts-to-buildship](https://cloud.githubusercontent.com/assets/1614482/14162193/2bd22532-f71c-11e5-840f-8cf7db78e3e9.png)

The links https://github.com/eclipse/buildship/wiki/Migration-guide-from-STS-Gradle-to-Buildship however does not list Known limitations of BuildShip Gradle integration:

- http://docs.spring.io/sts/nan/v372/NewAndNoteworthy.html

    Bug 471728: BuildShip does not integrate with Eclipse WTP. While projects that use 'war' packaging can be created using our wizards, such projects are not officialy supported and consequently will not be correctly configured by BuildShip.
    Bug 482315: Running a BuildShip project with "Run As Java Application" or "Run as Spring Boot App", the runtime classpath will be incorrect and contain 'test' dependencies. Note: this is not a problem specific only to "BuildShip". "STS Gradle Integration" is also affected as this issue stems from a limitation of the Gradle Tooling API that both use.
    Bug 468244: BuildShip lacks a mechanism for third-party tooling providers to participate in configuring a project. STS uses such a mechanism to configure the JDT Annotation Processor when spring-boot-configration-processor is present on a project's classpath. This automatic configuration currently only works with "STS Gradle Integration" but not "BuildShip". If you make use of the '@ConfigurationProperties' annotations in your code, this means that these annotations will not be processed as part of Eclipse workspace builds unless you manually configure JDT APT.

I think you should reference latest NewAndNoteworthy doc to show full picture (not all users read NewAndNoteworthy)

**Comment by kdvolder** [comment]
That dialog is not from us, but from BuildShip. (I.e. it is buildship that is showing this info. not STS).

The information they do show on their migration document does more or less cover all the points even if the wording isn't exactly the same. 

Still, if you would like them to change some of the wording you should do so via a bug against BuildShip on the [eclipse bugzilla](https://bugs.eclipse.org/bugs/).

**Comment by paulvi** [comment]
Raised as https://bugs.eclipse.org/bugs/show_bug.cgi?id=491011
