### ISSUE TITLE
Plugin cannot find gradle-internal class with gradle >=2.2

### ISSUE THREAD

**Issue by yoqto** [spring-projects/eclipse-integration-gradle#84]
It seems the plugin doesn't work properly when I use it with gradle 2.2(.1) (configured by Window - Preferences - Gradle, Gradle Distribution - Folder: /.../gradle-2.2.1) Starting Eclipse, I'm greeted by mulitple error messages that are logged [like this](https://gist.github.com/yoqto/dc2dff15e1c01baa06c3). These messages reappear every now and then.

Changing the configuration back to gradle 2.1 and restarting Eclipse, this error doesn't appear anymore and I can work on projects just fine.

As far as I can see, this is because the offending class has been moved in gradle/gradle@c1be1790d46b5c2116b257c7bda4719fe61978b7. According to `git tag --contains`, this change landed in 2.2 and, subsequently, the 2.3 release candidates as well.

I've tested with Eclipse Luna and Gradle IDE 3.6.4.201502031843-CI-B30.

**Comment by kdvolder** [comment]
Maybe upgrading to newer version of tooling API might fix the problem. If not then it needs to be reported as a bug to Gradle itself as the error comes from inside the Tooling API.

**Comment by kdvolder** [comment]
Sorry didn't mean to close this. clicked wrong button.

**Comment by kdvolder** [comment]
I have update tooling API version to 2.2.1. Could you please try updating your Gradle tools from nightly update site to see if it fixes the problem.

Update site is http://dist.springsource.com/snapshot/TOOLS/gradle/nightly

**Comment by yoqto** [comment]
I've upgraded to build 31 and sadly, no, that doesn't fix it. Still having 2.1 configured (and restarting Eclipse and killing the gradle daemon), there are no error messages.

Then I changed the path to a 2.2 installation, shut down Eclipse, killed the daemon, restarted Eclipse and voilà, the error messages still show up for tasks "Update Gradle Classpath for *projectName*".

**Comment by kdvolder** [comment]
Unfortunately there's nothing more that can be done on our (STS Tooling) side. This should be filed as a bug against the tooling API.

**Comment by kdvolder** [comment]
Posted a forum question to gradle forums: we can continue to follow up there. Closing this issue.

http://forums.gradle.org/gradle/topics/java-lang-classnotfoundexception-org-gradle-api-internal-artifacts-component-defaultmodulecomponentselector?rfm=1

**Comment by yoqto** [comment]
Thank you for the quick response. I think I'm misunderstanding something here, though.

Running the updateLibs command locally on the cloned eclipse-integration-gradle gradle file, I'm hit with a compilation error because class StsEclipseProjectModelBuilder in this repository is referencing classes DefaultModuleComponentIdentifier, DefaultModuleComponentSelector and JvmLibrary (see previously linked commit and gradle/gradle/0247f8b627ebb8660ad2c3d16ee32cd997632d60) with their old package paths. This is also what the stack trace I linked read to me.

The way I see it, this should be fixable by adapting the ModelBuilder class in this repository, not the upstream tooling API itself. Could you please clarify? I think the connection between these components isn't that clear to me.

**Comment by kdvolder** [comment]
Let me take another look, maybe I jumped to the wrong conclusion. Reopening.

**Comment by kdvolder** [comment]
You are probably right. Problem is coming from the 'Custom Model'. It doesn't show up as an error in my  build but it does when I run the regression tests on the custom model.

You could try disabling the Custom Model feature from Gradle preferences. (You have this enabled right?).

I can probably apply the fix you suggested but... that will probably break compatibility with 2.1.x.

**Comment by kdvolder** [comment]
I've applied some changes based on your observations. Also found a few more stray references in version 2.1 that needed replacing. Also changed the UI prefs page (it now states that custom tooling model requires 2.2 as I think the changes that were just made mean that is the case).

If you could please try CI build 34 (should be finished in a minute or two) from nightly again and let me know if this fixes your problem.

Thanks.

**Comment by yoqto** [comment]
Yep, looks fixed to me. With CI build 35:
2.1 with custom model -> errors
2.1 without custom model -> no errors
2.2 with & without custom model -> no errors

Thank you! :+1:

**Comment by kdvolder** [comment]
Thanks for confirming the fix. Closing.
