### ISSUE TITLE
the gradle java process don't quit when eclipse was closed

### ISSUE THREAD

**Issue by wayshall** [spring-projects/eclipse-integration-gradle#86]
I use eclipse kelper + eclipse-integration-gradle 3.6.3 
the eclipse would start a detached java process when I use gradle plugin related functions,
such as refresh dependencies.
and the java process will not quite when the refresh action has finished, 
even I close the eclipse, the java process still exist in task manager.

**Comment by kdvolder** [comment]
This is 'by design'. The Tooling API owns the daemon and provides no means for STS to terminate it.
The daemon will go away on its own after some time of inactivity (though it may be quite a long time).

**Comment by wayshall** [comment]
thanks!
I have been used m2e before.
m2e start a detached java process and close it when the action was done.
So, I have mistaked that it's a issue.
