### ISSUE TITLE
http proxy Ineffective

### ISSUE THREAD

**Issue by midstr** [spring-projects/eclipse-integration-gradle#87]
![11](https://cloud.githubusercontent.com/assets/3962423/6840106/992ca474-d3ad-11e4-9408-1f6c6d88a492.png)

i do like the Screenshot, but it lost my jvm httproxy options in daemon log ,and i can't download any jar...:

11:29:21.641 [INFO] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=eae78d3c-4665-45c1-85f4-a680227d3a48,javaHome=C:\Program Files\Java\jdk1.7.0_75,daemonRegistryDir=D:\gradle-repos\daemon,pid=5112,idleTimeout=10800000,daemonOpts=-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant]

**Comment by midstr** [comment]
![22](https://cloud.githubusercontent.com/assets/3962423/6840146/34f39df4-d3ae-11e4-8a33-219a6d52bbe7.png)

**Comment by paulvi** [comment]
by the way, why not to put into `gradle.properties`

like
```
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=3213
systemProp.http.nonProxyHosts=fun.tv|localhost
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=3213
systemProp.https.nonProxyHosts=fun.tv|localhost
```

**Comment by midstr** [comment]
3ks.
I think i find the Issue: the default maven repository url is "https://mvnrepository.com/", my proxy didn't support https..

**Comment by paulvi** [comment]
Is proxy.tencent.com free to use?

**Comment by midstr** [comment]
yes,it's my company's inner proxy.
