### ISSUE TITLE
Gradle IDE upgrade from 3.6.4 to 3.7.0 fails for missing dependencies

### ISSUE THREAD

**Issue by davidmichaelkarr** [spring-projects/eclipse-integration-gradle#92]
I wrote the following SO question for the same problem: http://stackoverflow.com/questions/31210706/pending-upgrade-of-eclipse-gradle-ide-from-v3-6-4-to-v3-7-0-fails-with-missing-d .

I've been running version v3.6.4 of the Gradle IDE in my Win7 Luna instance for some time.  A few days ago I noticed the availability of a new 3.7.0 version.  Unfortunately, it fails to install, with the following error:

    An error occurred while collecting items to be installed
    session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
    No repository found containing: osgi.bundle,org.springsource.ide.eclipse.gradle.core,3.7.0.201506251228-RELEASE
    No repository found containing: osgi.bundle,org.springsource.ide.eclipse.gradle.toolingapi,3.7.0.201506251228-RELEASE
    No repository found containing: osgi.bundle,org.springsource.ide.eclipse.gradle.ui,3.7.0.201506251228-RELEASE
    No repository found containing: osgi.bundle,org.springsource.ide.eclipse.gradle.ui.taskview,3.7.0.201506251228-RELEASE
    No repository found containing: org.eclipse.update.feature,org.springsource.ide.eclipse.gradle.feature,3.7.0.201506251228-RELEASE

Since the first time this failed a few days ago, I've tried several times, all with the same result.

**Comment by kdvolder** [comment]
How are you installing? From marketplace? From a specific update site? I can't try to reproduce the problem. I downloaded Eclipse luna and installed e-i-gradle from marketplace without a problem.

**Comment by davidmichaelkarr** [comment]
I already had 3.6.4 installed, and I'm just trying to update.  I likely installed it from an update site, and it was quite a while ago. I have update site <http://download.springsource.com/release/TOOLS/update/e4.4> in my update sites list, so I imagine I got it from there. I sure wish Eclipse would store metadata of where plugins were installed from.

Note that the Gradle IDE is the only installed plugin I have from the springsource package space.

I imagine one possible workaround might be to uninstall it and then reinstall it.  I hope that won't mess me up further.

**Comment by kdvolder** [comment]
It could be a 'caching' issue. I've seen similar errors like these and it looks like for some reason Eclipse thinks some specific version of a plugin exists on an update site, but its not actually there.

This can happen if eclipse has somehow cached an old 'summary' of an update site.

You can try to go to the 'Available Update Sites' in the preferences and use the 'Reload' button on that preferences dialog to 'refresh' the cache for the update site(s).

Then try again to install/update.

**Comment by davidmichaelkarr** [comment]
Ah, very good.  That did it. That goes in my toolbox. :)
