### ISSUE TITLE
Offline installation requires 

### ISSUE THREAD

**Issue by weisljl89** [spring-projects/eclipse-integration-gradle#95]
Master, can provide the eclipse offline installation package, online installation network too slow, and easy to get wrong!!!! This should be the needs of the broad masses！！

**Comment by paulvi** [comment]
Have you tried offline zip for STS ? https://spring.io/tools/sts/all

**Comment by kdvolder** [comment]
As paul points out the downloadable update site he points to should work for you. If not please explain why and maybe we can fix it. Closing this for now.

**Comment by weisljl89** [comment]
Thanks  Your!
According to your reminder, became the installation:

1, go to https://spring.io/tools/sts/all to download source maximizes - tool - suite - 3.7.0. RELEASE - e4.5 - updatesite. Zip the file, and extract the file

2, under the root directory of the eclipse, to create a custom gradle plugin directory, create plugins, features in this directory

3 the open_source_licenses, according to https://github.com/spring-projects/eclipse-integration-gradle. TXT file description,

SECTION 3: the Eclipse Public License V1.0
> > > org.apache.com mons. IO - 2.0.1
> > > org.springsource.ide.eclipse.commons.com pletions - 3.7.0
> > > org.springsource.ide.eclipse.com mons. Configurator - 3.7.0
> > > org.springsource.ide.eclipse.com mons. Content. The core - 3.7.0
> > > org.springsource.ide.eclipse.com mons. Core - 3.7.0
> > > org.springsource.ide.eclipse.com mons. Frameworks. The core - 3.7.0
> > > org.springsource.ide.eclipse.com mons. Frameworks. The UI - 3.7.0
> > > org.springsource.ide.eclipse.com mons. Livexp - 3.7.0
> > > org.springsource.ide.eclipse.com mons. UI - 3.7.0

These files can be found in the first step in the download file, copy these files to a custom plugins directory in the directory

4, in the download file to find the words with gradle jar file copy to the corresponding plugins, features

5, start eclipse in Windows - > Preferences can view Gradle, installed correctly

**Comment by paulvi** [comment]
Read books how to express tech issues and format using Markdown.
