### ISSUE TITLE
Gradle plugin trying to download gradle.zip from internet even though Gradle Home pointed to local folder

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-projects/eclipse-integration-gradle#97]
Hi, 
I have installed STS-3.4.0 and installed Gradle plugin. Also I have downloaded gradle-2.1.zip and extracted to my local folder, say D:\gradle-2.1. 
I have configured Gradle Home in Window -> Preferences -> Gradle -> Gradle Distribution 
Selected Folder and set the path "D:\gradle-2.1"

Now when I try to create a Gradle Project, it is trying to download gradle.zip from internet and getting the following error as my corporate proxy blocks all .zip downloads.

Server returned HTTP response code: 403 for URL: http://downloads.gradle.org/distributions/gradle-2.1-all.zip

Ideally it should not try to download gradle.zip as I have configured to use local gradle folder location.

**Comment by kdvolder** [comment]
Ah, yes, I see what's happening. The reason for downloading the zip is to fetch the 'quickstart' sample project which it uses as one of the templates for creating a new project. 

The sample code is fetched independently from the configured distribution as not al distributions contain the samples, and we use this sample from a very specific distribution zip.

The easiest way to fix this bug is probably to copy quickstart sample code and bundle it into the tools so it doesn't need to be downloaded.

**Comment by sivaprasadreddy** [comment]
Thanks for the insight.
Is there any hack that I can apply to get it working? Or is there any plans to fix this in future releases?

**Comment by kdvolder** [comment]
> Is there any hack that I can apply to get it working?

The only thing I can think of is that you have to get the download to work through the firewall somehow. Maybe you can do so by configuring network proxies in Eclipse or setting proxy related system properties.  

> Or is there any plans to fix this in future releases?

Yes, but I can't make any promises. I am busy with many things and in the long run these tools are probably going to be dropped in favor of Gradle's Buildship, so fixing issues on this project aren't very high on my priority list at the moment.

**Comment by kdvolder** [comment]
I've created a ticket in our Jira tracker (we don't really use the github issue tracker as our main tracker). I've targetted a fix for 3.7.2 release. If I have time I'll try and put a fix in.

Issue: https://issuetracker.springsource.com/browse/STS-4203

Closing this one as a 'duplicate'.

**Comment by yinyinnie** [comment]
change the http to https

**Comment by elviselle** [comment]
Hi, yinyinnie,
Where is the configuration to change the http to https?
